import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createServer } from 'vite';

await mkdir('test-results', { recursive: true });
process.env.WEDDING_DATA_DIR = await mkdtemp(resolve('test-results/isolated-'));
process.env.ADMIN_USERNAME = 'test-organizer';
process.env.ADMIN_PASSWORD = 'isolated-test-password';
const testPort=Number(process.env.WEDDING_TEST_PORT || 5174);
const server = await createServer({ server: { host:'127.0.0.1', port:testPort, strictPort:true } });
await server.listen();
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const base = `http://127.0.0.1:${testPort}`;
let createdId;
let originalSettings;
try {
  await page.goto(base);
  await page.getByRole('button', { name: 'Ahmed Ali' }).waitFor();
  await page.evaluate(() => document.fonts.ready);
  await page.getByRole('heading', {name:'Wajid Ali',exact:true}).waitFor();
  assert.match(await page.locator('.w-bismillah').textContent(), /بِسْمِ/);
  await page.getByRole('button', {name:'Walima 03'}).click();
  assert.equal(await page.getByRole('button', {name:'Walima 03'}).getAttribute('aria-pressed'),'true');
  await page.getByRole('heading', {name:'Together, with grateful hearts.'}).waitFor();
  await page.getByRole('button', {name:'Mehndi 01'}).click();
  await page.screenshot({ path: 'test-results/home-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Usman Khan' }).click();
  await page.getByRole('heading', { name: 'Usman Khan' }).waitFor();
  assert.equal(await page.locator('.event-card').count(), 1);
  assert.equal(await page.locator('.event-card h3').textContent(), 'Baraat');
  assert.equal(await page.locator('.family-badge').count(), 0);
  await page.getByRole('button', { name: 'Back to guest list' }).click();
  await page.getByRole('button', { name: 'Ahmed Ali' }).click();
  await page.getByRole('heading', { name: 'Ahmed Ali' }).waitFor();
  assert.equal(await page.locator('.event-card').count(), 3);
  assert.equal(await page.locator('.family-badge').count(), 1);
  const calendarPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Add to calendar'}).first().click();
  const calendar=await calendarPromise;
  const calendarText=await readFile(await calendar.path(),'utf8');
  assert.match(calendarText,/DTSTART:20261217T140000Z/);
  assert.match(calendarText,/SUMMARY:Wajid Ali/);
  await page.screenshot({ path: 'test-results/invitation-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 375, height: 812 });
  await page.screenshot({ path: 'test-results/invitation-mobile.png', fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.goto(base);
  await page.getByRole('button', { name: 'Ahmed Ali' }).waitFor();
  await page.screenshot({ path: 'test-results/home-mobile.png', fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('textbox', { name: 'Find your name' }).fill('not-on-the-list');
  await page.getByText('No name found.', { exact: false }).waitFor();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${base}/backend`);
  await page.getByLabel('Username', { exact: true }).fill('test-organizer');
  await page.getByLabel('Password', { exact: true }).fill('isolated-test-password');
  await page.screenshot({ path: 'test-results/backend-login.png', fullPage: true });
  await page.getByRole('button', { name: 'Enter family dashboard' }).click();
  await page.getByRole('heading', { name: 'The family dashboard.' }).waitFor();
  originalSettings = (await (await page.request.get(`${base}/api/admin`)).json()).settings;
  await page.screenshot({ path: 'test-results/admin-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Add new guest', exact: true }).click();
  await page.getByLabel('Guest name', { exact: true }).fill('QA Wedding Guest');
  await page.getByRole('button', { name: 'Select all three functions' }).click();
  await page.getByLabel('Invite with family').check();
  await page.screenshot({ path:'test-results/add-guest-desktop.png', fullPage:true });
  await page.getByRole('button', { name: 'Create invitation' }).click();
  await page.getByRole('button', { name: 'Edit QA Wedding Guest' }).waitFor();
  const admin = await (await page.request.get(`${base}/api/admin`)).json();
  createdId = admin.guests.find(g => g.name === 'QA Wedding Guest').id;
  await page.getByRole('tab', { name: 'Dates & venues' }).click();
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel(/^Date/).fill('2026-12-17');
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel('Venue', { exact:true }).fill('Royal Marquee');
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel('Address', {exact:true}).fill('Garden Road, Lahore, Pakistan');
  await page.getByRole('button',{name:'Choose pin on map'}).first().click();
  await page.getByRole('button',{name:'Bahria Town Lahore',exact:true}).click();
  await page.getByRole('textbox',{name:'Search Google landmarks'}).fill('Life Line Med Mart');
  await page.getByRole('button',{name:'Search',exact:true}).click();
  assert.match(new URL(await page.locator('iframe[title="Google Maps landmarks and venue preview"]').getAttribute('src')).searchParams.get('q'),/Life Line Med Mart, Bahria Town Lahore/);
  await page.getByLabel('Google Maps link or coordinates',{exact:true}).fill('https://www.google.com/maps/place/Venue/@30,70,15z/data=!3d31.38136!4d74.18635');
  await page.getByRole('button',{name:'Preview this pin'}).click();
  await page.getByText('31.381360, 74.186350',{exact:true}).waitFor();
  assert.equal(new URL(await page.locator('iframe[title="Google Maps landmarks and venue preview"]').getAttribute('src')).searchParams.get('q'),'31.38136,74.18635');
  await page.locator('.map-picker-dialog').screenshot({path:'test-results/google-landmarks-desktop.png'});
  await page.setViewportSize({width:375,height:812});
  await page.locator('.map-picker-dialog').evaluate(el=>{el.scrollTop=0;});
  await page.locator('.map-picker-dialog').screenshot({path:'test-results/google-landmarks-mobile.png'});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('tab',{name:'Pin picker',exact:true}).click();
  for(const [area,south,north,west,east] of [['Bahria Town Lahore',31.35,31.41,74.16,74.22],['Manga Mandi',31.28,31.32,74.05,74.09],['Raiwind',31.23,31.27,74.19,74.23]]){
    await page.getByRole('button',{name:area,exact:true}).click();
    assert(await page.getByRole('button',{name:'Use this pin',exact:true}).isDisabled());
    await page.getByRole('button',{name:'Place pin at map center'}).click();
    const [lat,lng]=(await page.locator('.pin-position [role=status]').textContent()).split(',').map(Number);
    assert(lat>south&&lat<north&&lng>west&&lng<east,`Map center must be in ${area}`);
  }
  await page.getByRole('button',{name:'Bahria Town Lahore',exact:true}).click();
  await page.locator('.pin-map').click({position:{x:180,y:180}});
  await page.getByRole('button',{name:'Use this pin'}).click();
  await page.locator('.pin-saved').first().waitFor();
  await page.getByRole('button', { name: 'Save all details' }).click();
  await page.getByText('Details saved. Guest cards will update automatically.').waitFor();
  await page.screenshot({ path: 'test-results/settings-desktop.png', fullPage: true });
  const invitationPage = await browser.newPage({ viewport: { width: 375, height: 812 } });
  await invitationPage.goto(`${base}/?invite=${createdId}`);
  await invitationPage.getByRole('heading', { name: 'QA Wedding Guest' }).waitFor();
  const whatsapp=invitationPage.getByRole('link',{name:'Contact family on WhatsApp'});
  assert.equal(new URL(await whatsapp.getAttribute('href')).pathname,'/923174539300');
  await invitationPage.getByRole('radio',{name:'Joyfully accepts'}).check();
  await invitationPage.route(`**/api/invitation/${createdId}/rsvp`,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Please try again.'})}),{times:1});
  await invitationPage.getByRole('button',{name:'Send RSVP',exact:true}).click();
  await invitationPage.getByRole('alert').filter({hasText:'Please try again.'}).waitFor();
  assert.equal((await (await invitationPage.request.get(`${base}/api/invitation/${createdId}`)).json()).guest.rsvp,null);
  await invitationPage.getByRole('button',{name:'Send RSVP',exact:true}).click();
  await invitationPage.getByText('Thank you! We look forward to celebrating with you.',{exact:true}).waitFor();
  await invitationPage.reload();
  await invitationPage.getByRole('radio',{name:'Joyfully accepts'}).waitFor();
  assert(await invitationPage.getByRole('radio',{name:'Joyfully accepts'}).isChecked());
  assert.equal((await (await page.request.get(`${base}/api/admin`)).json()).guests.find(g=>g.id===createdId).rsvp.status,'accepted');
  await invitationPage.getByRole('radio',{name:'Regretfully declines'}).check();
  await invitationPage.getByRole('button',{name:'Update RSVP',exact:true}).click();
  await invitationPage.getByText('Thank you for letting us know. You will be missed.',{exact:true}).waitFor();
  await invitationPage.locator('.w-rsvp').screenshot({path:'test-results/rsvp-mobile.png'});
  await invitationPage.getByText('17 December 2026', { exact: true }).waitFor();
  assert.match(await invitationPage.locator('.event-mehndi .venue').textContent(),/Royal Marquee/);
  await invitationPage.getByText('Garden Road, Lahore, Pakistan', {exact:true}).waitFor();
  const pinnedSettings=(await (await page.request.get(`${base}/api/admin`)).json()).settings;
  const pin=pinnedSettings.events[0].location;
  assert(Number.isFinite(pin.lat) && Number.isFinite(pin.lng));
  const map=invitationPage.locator('iframe[title="Mehndi venue map"]');
  assert.equal(new URL(await map.getAttribute('src')).searchParams.get('q'),`${pin.lat},${pin.lng}`);
  assert.equal(new URL(await invitationPage.getByRole('link',{name:'Directions',exact:true}).getAttribute('href')).searchParams.get('destination'),`${pin.lat},${pin.lng}`);
  await invitationPage.evaluate(()=>{
    Object.defineProperty(navigator,'share',{value:undefined,configurable:true});
    Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copiedLocation=text;}},configurable:true});
  });
  await invitationPage.getByRole('button',{name:'Share location'}).click();
  await invitationPage.getByText('Location link copied. Ready to share.').waitFor();
  assert.equal(new URL(await invitationPage.evaluate(()=>window.copiedLocation)).searchParams.get('query'),`${pin.lat},${pin.lng}`);
  assert.equal(await invitationPage.locator('.event-card').count(), 3);
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel(/^Date/).fill('2026-12-18');
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel('Venue', { exact:true }).fill('Rose Banquet');
  await page.getByRole('button', { name:'Save all details' }).click();
  await page.waitForFunction(() => document.querySelector('.settings-bottom button').disabled);
  await invitationPage.evaluate(() => window.dispatchEvent(new Event('focus')));
  await invitationPage.locator('.event-mehndi').getByText('18 December 2026', { exact:true }).waitFor();
  await invitationPage.waitForFunction(()=>document.querySelector('.event-mehndi .venue')?.textContent.includes('Rose Banquet'));
  await page.bringToFront();
  await page.getByRole('tab', { name: 'Guest list' }).focus();
  await page.getByRole('tab', { name: 'Guest list' }).press('Enter');
  await page.locator('#guests-panel:not([hidden])').waitFor();
  await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
  const guestRow=page.getByRole('row').filter({has:page.getByRole('button',{name:'Edit QA Wedding Guest',exact:true})});
  await guestRow.getByText('Declined',{exact:true}).waitFor();
  await page.getByLabel('Filter by RSVP').selectOption('accepted');
  assert.equal(await page.getByRole('button',{name:'Edit QA Wedding Guest',exact:true}).count(),0);
  await page.getByLabel('Filter by RSVP').selectOption('declined');
  await page.getByRole('button',{name:'Edit QA Wedding Guest',exact:true}).waitFor();
  await page.getByLabel('Filter by RSVP').selectOption('all');
  await page.screenshot({path:'test-results/rsvp-admin.png',fullPage:true});
  await page.getByRole('button', { name: 'Edit QA Wedding Guest' }).click();
  await page.getByLabel('Mehndi', { exact: true }).uncheck();
  await page.getByLabel('Baraat', { exact: true }).uncheck();
  await page.getByLabel('Without family').check();
  await page.getByRole('button', { name: 'Save changes' }).click();
  await page.getByRole('button', { name: 'Edit QA Wedding Guest' }).waitFor();
  await invitationPage.reload();
  await invitationPage.getByRole('heading', { name: 'QA Wedding Guest' }).waitFor();
  assert.equal(await invitationPage.locator('.event-card').count(), 1);
  assert.equal(await invitationPage.locator('.event-card h3').textContent(), 'Walima');
  assert.equal(await invitationPage.locator('.family-badge').count(), 0);
  assert(await invitationPage.getByRole('radio',{name:'Regretfully declines'}).isChecked());
  await page.setViewportSize({ width: 375, height: 812 });
  await page.screenshot({ path: 'test-results/admin-mobile.png', fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('button', { name:'Add new guest' }).click();
  await page.screenshot({ path:'test-results/add-guest-mobile.png', fullPage:true });
  await page.getByRole('button', { name:'Close guest form' }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Remove QA Wedding Guest' }).click();
  await page.getByText('Guest removed.', { exact: true }).waitFor();
  assert.equal((await page.request.get(`${base}/api/invitation/${createdId}`)).status(), 404);
  createdId = null;
  await page.getByRole('tab', { name:'Dates & venues' }).click();
  await page.screenshot({ path:'test-results/settings-mobile.png', fullPage:true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('button', { name:'Sign out' }).click();
  await page.getByLabel('Username', { exact:true }).waitFor();
  assert.equal((await page.request.get(`${base}/api/admin`)).status(),401);
  const motionPage = await browser.newPage({ viewport:{ width:375,height:812 }, reducedMotion:'no-preference' });
  await motionPage.goto(base);
  await motionPage.getByRole('button', { name:'Ahmed Ali' }).click();
  await motionPage.locator('.envelope-overlay').waitFor();
  await motionPage.getByRole('heading', { name:'Ahmed Ali' }).waitFor();
  assert.equal(await motionPage.locator('.envelope-overlay').count(),0);
  for (const viewport of [{width:320,height:740},{width:812,height:375}]) {
    await motionPage.setViewportSize(viewport);
    await motionPage.goto(base);
    await motionPage.getByRole('button', { name:'Ahmed Ali' }).waitFor();
    assert(await motionPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Home overflow at ${viewport.width}px`);
  }
  assert.deepEqual(errors, []);
  console.log('PASS: /backend login, guest CRUD, family options, dates, venue/address, map pin, Google directions, share location, open-card refresh, responsive layouts, envelope animation, logout.');
} catch(error) {
  await page.screenshot({path:'test-results/browser-failure.png',fullPage:true});
  await writeFile('test-results/browser-failure.txt',await page.locator('body').innerText());
  throw error;
} finally {
  await browser.close();
  await server.close();
}
