import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createServer } from 'vite';

await mkdir('test-results', { recursive: true });
process.env.WEDDING_DATA_DIR = await mkdtemp(resolve('test-results/isolated-'));
process.env.ADMIN_USERNAME = 'test-organizer';
process.env.ADMIN_PASSWORD = 'isolated-test-password';
const testPort=Number(process.env.WEDDING_TEST_PORT || 5174);
const server = await createServer({ server: { host:'127.0.0.1', port:testPort, strictPort:true } });
await server.listen();
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const base = `http://127.0.0.1:${testPort}`;
let createdId;
let originalSettings;
try {
  await page.goto(base);
  await page.getByRole('link',{name:'Family sign-in to view guest cards'}).waitFor();
  assert.equal(await page.getByRole('textbox',{name:'Find your name'}).count(),0);
  assert.equal(await page.locator('.w-guest').count(),0);
  const publicData=await (await page.request.get(base+'/api/public')).json();
  assert.deepEqual(publicData.guests,[]);assert.equal(publicData.canBrowse,false);
  await page.getByRole('link',{name:'Family sign-in to view guest cards'}).click();
  await page.getByLabel('Username',{exact:true}).fill('test-organizer');
  await page.getByLabel('Password',{exact:true}).fill('isolated-test-password');
  await page.getByRole('button',{name:'View guest invitations',exact:true}).click();
  await page.getByRole('button', { name: 'Ahmed Ali' }).waitFor();
  await page.evaluate(() => document.fonts.ready);
  await page.getByRole('heading', {name:'Wajid Ali',exact:true}).waitFor();
  assert.match(await page.locator('.w-bismillah').textContent(), /بِسْمِ/);
  await page.getByRole('button', {name:'Walima 03'}).click();
  assert.equal(await page.getByRole('button', {name:'Walima 03'}).getAttribute('aria-pressed'),'true');
  await page.getByRole('heading', {name:'Together, with grateful hearts.'}).waitFor();
  await page.getByRole('button', {name:'Mehndi 01'}).click();
  await page.screenshot({ path: 'test-results/home-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Usman Khan' }).click();
  await page.getByRole('heading', { name: 'Usman Khan' }).waitFor();
  assert.equal(await page.locator('.event-card').count(), 1);
  assert.equal(await page.locator('.event-card h3').textContent(), 'Baraat');
  assert.equal(await page.locator('.family-badge').count(), 0);
  await page.getByRole('button', { name: 'Back to guest list' }).click();
  await page.getByRole('button', { name: 'Ahmed Ali' }).click();
  await page.getByRole('heading', { name: 'Ahmed Ali' }).waitFor();
  assert.equal(await page.locator('.event-card').count(), 3);
  assert.equal(await page.locator('.family-badge').count(), 1);
  const calendarPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Add to calendar'}).first().click();
  const calendar=await calendarPromise;
  const calendarText=await readFile(await calendar.path(),'utf8');
  assert.match(calendarText,/DTSTART:20261217T140000Z/);
  assert.match(calendarText,/SUMMARY:Wajid Ali/);
  await page.screenshot({ path: 'test-results/invitation-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 375, height: 812 });
  await page.screenshot({ path: 'test-results/invitation-mobile.png', fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.goto(base);
  await page.getByRole('button', { name: 'Ahmed Ali' }).waitFor();
  await page.screenshot({ path: 'test-results/home-mobile.png', fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('textbox', { name: 'Find your name' }).fill('not-on-the-list');
  await page.getByText('No name found.', { exact: false }).waitFor();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${base}/backend`);
  await page.getByRole('button',{name:'Sign out'}).click();
  await page.getByLabel('Username', { exact: true }).fill('test-organizer');
  await page.getByLabel('Password', { exact: true }).fill('isolated-test-password');
  await page.screenshot({ path: 'test-results/backend-login.png', fullPage: true });
  await page.getByRole('button', { name: 'Enter family dashboard' }).click();
  await page.getByRole('heading', { name: 'The family dashboard.' }).waitFor();
  originalSettings = (await (await page.request.get(`${base}/api/admin`)).json()).settings;
  await page.screenshot({ path: 'test-results/admin-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Add new guest', exact: true }).click();
  await page.getByLabel('Guest name', { exact: true }).fill('QA Wedding Guest');
  await page.getByRole('button', { name: 'Select all three functions' }).click();
  await page.getByLabel('Invite with family').check();
  await page.screenshot({ path:'test-results/add-guest-desktop.png', fullPage:true });
  await page.getByRole('button', { name: 'Create invitation' }).click();
  await page.getByRole('button', { name: 'Edit QA Wedding Guest' }).waitFor();
  const admin = await (await page.request.get(`${base}/api/admin`)).json();
  createdId = admin.guests.find(g => g.name === 'QA Wedding Guest').id;
  const shareField=page.getByRole('textbox',{name:'Invitation link for QA Wedding Guest'});
  assert.equal(await shareField.inputValue(),base+'/invite/qa-wedding-guest/'+createdId);
  await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copiedInvitation=text;}},configurable:true});});
  const warmedPreview=page.waitForResponse(response=>response.url()===base+'/invite/qa-wedding-guest/'+createdId && response.request().resourceType()==='fetch');
  await page.getByRole('button',{name:'Copy link for QA Wedding Guest',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.copiedInvitation),base+'/invite/qa-wedding-guest/'+createdId);
  assert((await (await warmedPreview).text()).includes('property="og:title"'));
  await page.getByRole('tab', { name: 'Dates & venues' }).click();
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel(/^Date/).fill('2026-12-17');
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel('Venue', { exact:true }).fill('Royal Marquee');
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel('Address', {exact:true}).fill('Garden Road, Lahore, Pakistan');
  await page.getByRole('button',{name:'Choose pin on map'}).first().click();
  assert.equal(await page.getByRole('tab',{name:'Google Maps & landmarks',exact:true}).getAttribute('aria-selected'),'true');
  await page.getByRole('tab',{name:'Pin picker',exact:true}).click();
  await page.locator('.pin-map').click({position:{x:180,y:180}});
  const coordinateInput=page.getByLabel('Google Maps link, Plus Code or address',{exact:true});
  assert.match(await coordinateInput.inputValue(),/^-?\d+\.\d+, -?\d+\.\d+$/);
  assert.equal(await page.getByRole('button',{name:'Use this pin',exact:true}).isEnabled(),true);
  const pasteLocation=async value=>{
    // The native insertion must not be cancelled; mobile input/autofill then
    // follows the same ordinary input event path exercised by fill().
    assert(await coordinateInput.evaluate(element=>element.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true}))));
    await coordinateInput.fill(value);
  };
  await pasteLocation('https://maps.app.goo.gl/nearby-hall');
  await page.getByRole('button',{name:'Use this location',exact:true}).click();
  const firstVenue=page.locator('.event-settings-grid .settings-panel').first();
  assert.equal(await firstVenue.getByLabel('Address',{exact:true}).inputValue(),'Garden Road, Lahore, Pakistan');
  assert.equal(await firstVenue.getByRole('link',{name:'Open in Maps',exact:true}).getAttribute('href'),'https://maps.app.goo.gl/nearby-hall');
  await page.getByRole('button',{name:'Save all details'}).click();
  await page.getByText('Details saved. Guest cards will update automatically.').waitFor();
  const landmarkEvent=(await (await page.request.get(base+'/api/admin')).json()).settings.events[0];
  assert.equal(landmarkEvent.location,null);
  assert.equal(landmarkEvent.mapUrl,'https://maps.app.goo.gl/nearby-hall');
  await firstVenue.getByRole('button',{name:'Adjust location pin'}).click();
  assert.equal(await coordinateInput.inputValue(),'https://maps.app.goo.gl/nearby-hall');
  await pasteLocation('https://www.google.com/maps/place/Manga+Mandi,+Pakistan/@31.2996906,74.0717447,18z/data=!4m6!3m5!1s0x39185706b071549d:0x2454ab657170f454!8m2!3d31.299426!4d74.0700372!16s%2Fg%2F1hc3kg8f2?entry=ttu');
  await page.getByText('Pin selected: 31.299426, 74.070037',{exact:true}).waitFor();
  assert.match(await coordinateInput.inputValue(),/Manga\+Mandi/);
  await pasteLocation('832G+9WX, District, Manga Mandi, Lahore, Pakistan');
  await page.getByText('Pin selected: 31.300987, 74.077359',{exact:true}).waitFor();
  assert.equal(await coordinateInput.inputValue(),'832G+9WX, District, Manga Mandi, Lahore, Pakistan');
  await pasteLocation('Al Jannat Shadi Hall, Manga Mandi');
  await page.getByText('Address search ready — check the matching place on Google Maps.').waitFor();
  assert.equal(await page.getByRole('button',{name:'Use this location',exact:true}).isEnabled(),true);
  assert.equal(new URL(await page.locator('iframe[title="Google Maps landmarks and venue preview"]').getAttribute('src')).searchParams.get('q'),'Al Jannat Shadi Hall, Manga Mandi');
  await pasteLocation('832G+9WX');
  await page.getByRole('alert').filter({hasText:'Include the town'}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Use this pin',exact:true}).isDisabled(),true);
  await coordinateInput.fill('');
  await coordinateInput.pressSequentially('31.30005, 74.07002');
  assert.equal(await coordinateInput.inputValue(),'31.30005, 74.07002');
  await coordinateInput.press('Enter');
  await page.getByText('Pin selected: 31.300050, 74.070020',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Bahria Town Lahore',exact:true}).click();
  assert.equal(await coordinateInput.inputValue(),'');
  await page.getByRole('tab',{name:'Google Maps & landmarks'}).click();
  await coordinateInput.fill('Life Line Med Mart, Bahria Town Lahore');
  await page.getByText('Address search ready — check the matching place on Google Maps.').waitFor();
  assert.match(new URL(await page.locator('iframe[title="Google Maps landmarks and venue preview"]').getAttribute('src')).searchParams.get('q'),/Life Line Med Mart, Bahria Town Lahore/);
  await coordinateInput.fill('https://www.google.com/maps/place/Venue/@30,70,15z/data=!3d31.38136!4d74.18635');
  await page.getByRole('button',{name:'Preview location'}).click();
  await page.getByText('Pin selected: 31.381360, 74.186350',{exact:true}).waitFor();
  assert.equal(new URL(await page.locator('iframe[title="Google Maps landmarks and venue preview"]').getAttribute('src')).searchParams.get('q'),'31.38136,74.18635');
  await page.locator('.map-picker-dialog').screenshot({path:'test-results/google-landmarks-desktop.png'});
  await page.setViewportSize({width:375,height:812});
  await page.locator('.map-picker-dialog').evaluate(el=>{el.scrollTop=0;});
  await page.locator('.map-picker-dialog').screenshot({path:'test-results/google-landmarks-mobile.png'});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('tab',{name:'Pin picker',exact:true}).click();
  for(const [area,south,north,west,east] of [['Bahria Town Lahore',31.35,31.41,74.16,74.22],['Manga Mandi',31.28,31.32,74.05,74.09],['Raiwind',31.23,31.27,74.19,74.23]]){
    await page.getByRole('button',{name:area,exact:true}).click();
    assert(await page.getByRole('button',{name:'Use this pin',exact:true}).isDisabled());
    await page.getByRole('button',{name:'Place pin at map center'}).click();
    const [lat,lng]=(await page.locator('.pin-position [role=status]').textContent()).replace('Pin selected: ','').split(',').map(Number);
    assert(lat>south&&lat<north&&lng>west&&lng<east,`Map center must be in ${area}`);
  }
  await page.getByRole('button',{name:'Bahria Town Lahore',exact:true}).click();
  await page.locator('.pin-map').click({position:{x:180,y:180}});
  await page.getByRole('button',{name:'Use this pin'}).click();
  await page.locator('.pin-saved').first().waitFor();
  await page.getByRole('button', { name: 'Save all details' }).click();
  await page.getByText('Details saved. Guest cards will update automatically.').waitFor();
  await page.screenshot({ path: 'test-results/settings-desktop.png', fullPage: true });
  const invitationPage = await browser.newPage({ viewport: { width: 375, height: 812 } });
  const shareHtml=await (await page.request.get(base+'/invite/qa-wedding-guest/'+createdId)).text();
  assert(shareHtml.includes('<title>Wajid Ali invites you, QA Wedding Guest, to his wedding</title>'));
  assert(shareHtml.includes('property="og:image"'));
  assert(!shareHtml.includes('Ahmed Ali'));
  const cardImage=await page.request.get(base+'/wedding-share-card-v2.jpg');
  assert.equal(cardImage.status(),200);assert.match(cardImage.headers()['content-type'],/image\/jpeg/);
  const guestRequests=[];
  invitationPage.on('request',request=>{if(request.url().includes('/api/'))guestRequests.push(request.url());});
  await invitationPage.goto(base+'/invite/qa-wedding-guest/'+createdId);
  await invitationPage.getByRole('heading', { name: 'QA Wedding Guest' }).waitFor();
  assert.equal(await invitationPage.getByRole('button',{name:'Back to guest list'}).count(),0);
  assert.equal(await invitationPage.getByRole('textbox',{name:'Find your name'}).count(),0);
  assert(!guestRequests.some(url=>url.includes('/api/public')||url.includes('/api/admin')));
  const privateDirectory=await (await invitationPage.request.get(base+'/api/public')).json();
  assert.deepEqual(privateDirectory.guests,[]);
  assert.equal(await invitationPage.title(),'Wajid Ali invites you, QA Wedding Guest, to his wedding');
  await invitationPage.evaluate(()=>{Object.defineProperty(navigator,'share',{value:async payload=>{window.sharedInvitation=payload;},configurable:true});});
  await invitationPage.getByRole('button',{name:'Share invitation',exact:true}).click();
  const shared=await invitationPage.evaluate(()=>window.sharedInvitation);
  assert.equal(shared.url,base+'/invite/qa-wedding-guest/'+createdId);
  assert.equal(shared.title,'Wajid Ali invites you, QA Wedding Guest, to his wedding');
  assert.equal(shared.text,shared.title);
  const whatsapp=invitationPage.getByRole('link',{name:'Contact family on WhatsApp'});
  assert.equal(new URL(await whatsapp.getAttribute('href')).pathname,'/923174539300');
  await invitationPage.getByRole('radio',{name:'Joyfully accepts'}).check();
  await invitationPage.route(`**/api/invitation/${createdId}/rsvp`,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Please try again.'})}),{times:1});
  await invitationPage.getByRole('button',{name:/جواب بھیجیں.*Send reply/}).click();
  await invitationPage.getByRole('alert').filter({hasText:'Please try again.'}).waitFor();
  assert.equal((await (await invitationPage.request.get(`${base}/api/invitation/${createdId}`)).json()).guest.rsvp,null);
  await invitationPage.getByRole('button',{name:/جواب بھیجیں.*Send reply/}).click();
  await invitationPage.getByText('Thank you! We look forward to celebrating with you.',{exact:true}).waitFor();
  await invitationPage.goto(base+'/?invite='+createdId);
  await invitationPage.getByRole('radio',{name:'Joyfully accepts'}).waitFor();
  assert(await invitationPage.getByRole('radio',{name:'Joyfully accepts'}).isChecked());
  assert.equal((await (await page.request.get(`${base}/api/admin`)).json()).guests.find(g=>g.id===createdId).rsvp.status,'accepted');
  await invitationPage.getByRole('radio',{name:'Regretfully declines'}).check();
  await invitationPage.getByRole('button',{name:/جواب تبدیل کریں.*Update reply/}).click();
  await invitationPage.getByText('Thank you for letting us know. You will be missed.',{exact:true}).waitFor();
  assert.equal(await invitationPage.locator('.w-rsvp [lang="ur"]').count(),3);
  assert.equal(await invitationPage.locator('.w-rsvp [lang="ur"]').evaluateAll(elements=>elements.every(el=>el.closest('.w-rsvp-option, .w-rsvp-submit'))),true);
  assert(await invitationPage.getByRole('button',{name:/جواب محفوظ ہے.*Reply saved/}).isDisabled());
  await invitationPage.locator('.w-rsvp').screenshot({path:'test-results/rsvp-mobile.png'});
  await invitationPage.getByText('17 December 2026', { exact: true }).waitFor();
  assert.match(await invitationPage.locator('.event-mehndi .venue').textContent(),/Royal Marquee/);
  await invitationPage.getByText('Garden Road, Lahore, Pakistan', {exact:true}).waitFor();
  const pinnedSettings=(await (await page.request.get(`${base}/api/admin`)).json()).settings;
  const pin=pinnedSettings.events[0].location;
  assert(Number.isFinite(pin.lat) && Number.isFinite(pin.lng));
  const map=invitationPage.locator('iframe[title="Mehndi venue map"]');
  assert.equal(new URL(await map.getAttribute('src')).searchParams.get('q'),`${pin.lat},${pin.lng}`);
  assert.equal(new URL(await invitationPage.getByRole('link',{name:'Directions',exact:true}).getAttribute('href')).searchParams.get('destination'),`${pin.lat},${pin.lng}`);
  await invitationPage.evaluate(()=>{
    Object.defineProperty(navigator,'share',{value:undefined,configurable:true});
    Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copiedLocation=text;}},configurable:true});
  });
  await invitationPage.getByRole('button',{name:'Share location'}).click();
  await invitationPage.getByText('Location link copied. Ready to share.').waitFor();
  assert.equal(new URL(await invitationPage.evaluate(()=>window.copiedLocation)).searchParams.get('query'),`${pin.lat},${pin.lng}`);
  assert.equal(await invitationPage.locator('.event-card').count(), 3);
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel(/^Date/).fill('2026-12-18');
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel('Venue', { exact:true }).fill('Rose Banquet');
  await page.getByRole('button', { name:'Save all details' }).click();
  await page.waitForFunction(() => document.querySelector('.settings-bottom button').disabled);
  await invitationPage.evaluate(() => window.dispatchEvent(new Event('focus')));
  await invitationPage.locator('.event-mehndi').getByText('18 December 2026', { exact:true }).waitFor();
  await invitationPage.waitForFunction(()=>document.querySelector('.event-mehndi .venue')?.textContent.includes('Rose Banquet'));
  await page.bringToFront();
  await page.getByRole('tab', { name: 'Guest list' }).focus();
  await page.getByRole('tab', { name: 'Guest list' }).press('Enter');
  await page.locator('#guests-panel:not([hidden])').waitFor();
  await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
  const guestRow=page.getByRole('row').filter({has:page.getByRole('button',{name:'Edit QA Wedding Guest',exact:true})});
  await guestRow.getByText('Declined',{exact:true}).waitFor();
  await page.getByLabel('Filter by RSVP').selectOption('accepted');
  assert.equal(await page.getByRole('button',{name:'Edit QA Wedding Guest',exact:true}).count(),0);
  await page.getByLabel('Filter by RSVP').selectOption('declined');
  await page.getByRole('button',{name:'Edit QA Wedding Guest',exact:true}).waitFor();
  await page.getByLabel('Filter by RSVP').selectOption('all');
  await page.screenshot({path:'test-results/rsvp-admin.png',fullPage:true});
  await page.getByRole('button', { name: 'Edit QA Wedding Guest' }).click();
  await page.getByLabel('Mehndi', { exact: true }).uncheck();
  await page.getByLabel('Baraat', { exact: true }).uncheck();
  await page.getByLabel('Without family').check();
  await page.getByRole('button', { name: 'Save changes' }).click();
  await page.getByRole('button', { name: 'Edit QA Wedding Guest' }).waitFor();
  await invitationPage.reload();
  await invitationPage.getByRole('heading', { name: 'QA Wedding Guest' }).waitFor();
  assert.equal(await invitationPage.locator('.event-card').count(), 1);
  assert.equal(await invitationPage.locator('.event-card h3').textContent(), 'Walima');
  assert.equal(await invitationPage.locator('.family-badge').count(), 0);
  assert(await invitationPage.getByRole('radio',{name:'Regretfully declines'}).isChecked());
  await page.setViewportSize({ width: 375, height: 812 });
  await page.screenshot({ path: 'test-results/admin-mobile.png', fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('button', { name:'Add new guest' }).click();
  await page.screenshot({ path:'test-results/add-guest-mobile.png', fullPage:true });
  await page.getByRole('button', { name:'Close guest form' }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Remove QA Wedding Guest' }).click();
  await page.getByText('Guest removed.', { exact: true }).waitFor();
  assert.equal((await page.request.get(`${base}/api/invitation/${createdId}`)).status(), 404);
  createdId = null;
  await page.getByRole('tab', { name:'Dates & venues' }).click();
  await page.screenshot({ path:'test-results/settings-mobile.png', fullPage:true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('button', { name:'Sign out' }).click();
  await page.getByLabel('Username', { exact:true }).waitFor();
  assert.equal((await page.request.get(`${base}/api/admin`)).status(),401);
  const motionPage = await browser.newPage({ viewport:{ width:375,height:812 }, reducedMotion:'no-preference' });
  await motionPage.goto(base+'/family');
  await motionPage.getByLabel('Username',{exact:true}).fill('test-organizer');
  await motionPage.getByLabel('Password',{exact:true}).fill('isolated-test-password');
  await motionPage.getByRole('button',{name:'View guest invitations',exact:true}).click();
  await motionPage.getByRole('button', { name:'Ahmed Ali' }).click();
  await motionPage.locator('.envelope-overlay').waitFor();
  await motionPage.getByRole('heading', { name:'Ahmed Ali' }).waitFor();
  assert.equal(await motionPage.locator('.envelope-overlay').count(),0);
  for (const viewport of [{width:320,height:740},{width:812,height:375}]) {
    await motionPage.setViewportSize(viewport);
    await motionPage.goto(base);
    await motionPage.getByRole('button', { name:'Ahmed Ali' }).waitFor();
    assert(await motionPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Home overflow at ${viewport.width}px`);
  }
  await motionPage.getByRole('button',{name:'Sign out of family view'}).click();
  await motionPage.getByRole('link',{name:'Family sign-in to view guest cards'}).waitFor();
  assert.equal(await motionPage.locator('.w-guest').count(),0);
  await invitationPage.goto(base+'/?preview='+createdId);
  await invitationPage.getByRole('link',{name:'Family sign-in to view guest cards'}).waitFor();
  assert.equal(await invitationPage.locator('.w-guest').count(),0);
  await invitationPage.goto(base+'/?invite=missing-invitation');
  await invitationPage.getByRole('alert').waitFor();
  assert.equal(await invitationPage.locator('.w-guest').count(),0);
  await invitationPage.goto(base);
  await invitationPage.getByRole('link',{name:'Family sign-in to view guest cards'}).waitFor();
  await invitationPage.screenshot({path:'test-results/private-home-mobile.png',fullPage:true});
  assert(await invitationPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.deepEqual(errors, []);
  console.log('PASS: /backend login, guest CRUD, family options, dates, venue/address, map pin, Google directions, share location, open-card refresh, responsive layouts, envelope animation, logout.');
} catch(error) {
  await page.screenshot({path:'test-results/browser-failure.png',fullPage:true});
  await writeFile('test-results/browser-failure.txt',await page.locator('body').innerText());
  throw error;
} finally {
  await browser.close();
  await server.close();
}
