import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createServer } from 'vite';

await mkdir('test-results', { recursive: true });
process.env.WEDDING_DATA_DIR = await mkdtemp(resolve('test-results/isolated-'));
process.env.ADMIN_USERNAME = 'test-organizer';
process.env.ADMIN_PASSWORD = 'isolated-test-password';
const server = await createServer({ server: { host:'127.0.0.1', port:5174, strictPort:true } });
await server.listen();
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const base = 'http://127.0.0.1:5174';
let createdId;
let originalSettings;
try {
  await page.goto(base);
  await page.getByRole('button', { name: 'Ahmed Ali' }).waitFor();
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: 'test-results/home-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Usman Khan' }).click();
  await page.getByRole('heading', { name: 'Usman Khan' }).waitFor();
  assert.equal(await page.locator('.event-card').count(), 1);
  assert.equal(await page.locator('.event-card h3').textContent(), 'Baraat');
  assert.equal(await page.locator('.family-badge').count(), 0);
  await page.getByRole('button', { name: 'Back to guest list' }).click();
  await page.getByRole('button', { name: 'Ahmed Ali' }).click();
  await page.getByRole('heading', { name: 'Ahmed Ali' }).waitFor();
  assert.equal(await page.locator('.event-card').count(), 3);
  assert.equal(await page.locator('.family-badge').count(), 1);
  await page.screenshot({ path: 'test-results/invitation-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 375, height: 812 });
  await page.screenshot({ path: 'test-results/invitation-mobile.png', fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.goto(base);
  await page.getByRole('button', { name: 'Ahmed Ali' }).waitFor();
  await page.screenshot({ path: 'test-results/home-mobile.png', fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('textbox', { name: 'Find your name' }).fill('not-on-the-list');
  await page.getByText('No name found.', { exact: false }).waitFor();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${base}/backend`);
  await page.getByLabel('Username', { exact: true }).fill('test-organizer');
  await page.getByLabel('Password', { exact: true }).fill('isolated-test-password');
  await page.screenshot({ path: 'test-results/backend-login.png', fullPage: true });
  await page.getByRole('button', { name: 'Enter family dashboard' }).click();
  await page.getByRole('heading', { name: 'The family dashboard.' }).waitFor();
  originalSettings = (await (await page.request.get(`${base}/api/admin`)).json()).settings;
  await page.screenshot({ path: 'test-results/admin-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Add new guest', exact: true }).click();
  await page.getByLabel('Guest name', { exact: true }).fill('QA Wedding Guest');
  await page.getByRole('button', { name: 'Select all three functions' }).click();
  await page.getByLabel('Invite with family').check();
  await page.screenshot({ path:'test-results/add-guest-desktop.png', fullPage:true });
  await page.getByRole('button', { name: 'Create invitation' }).click();
  await page.getByRole('button', { name: 'Edit QA Wedding Guest' }).waitFor();
  const admin = await (await page.request.get(`${base}/api/admin`)).json();
  createdId = admin.guests.find(g => g.name === 'QA Wedding Guest').id;
  await page.getByRole('tab', { name: 'Dates & venues' }).click();
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel(/^Date/).fill('2026-12-17');
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel('Venue', { exact:true }).fill('Royal Marquee');
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel('Address', {exact:true}).fill('Garden Road, Lahore, Pakistan');
  await page.getByRole('button',{name:'Choose pin on map'}).first().click();
  await page.getByLabel('Jump to city').selectOption('Lahore');
  await page.locator('.pin-map').click({position:{x:180,y:180}});
  await page.getByRole('button',{name:'Use this pin'}).click();
  await page.locator('.pin-saved').first().waitFor();
  await page.getByRole('button', { name: 'Save all details' }).click();
  await page.getByText('Details saved. Guest cards will update automatically.').waitFor();
  await page.screenshot({ path: 'test-results/settings-desktop.png', fullPage: true });
  const invitationPage = await browser.newPage({ viewport: { width: 375, height: 812 } });
  await invitationPage.goto(`${base}/?invite=${createdId}`);
  await invitationPage.getByRole('heading', { name: 'QA Wedding Guest' }).waitFor();
  await invitationPage.getByText('17 December 2026', { exact: true }).waitFor();
  assert.match(await invitationPage.locator('.event-mehndi .venue').textContent(),/Royal Marquee/);
  await invitationPage.getByText('Garden Road, Lahore, Pakistan', {exact:true}).waitFor();
  const pinnedSettings=(await (await page.request.get(`${base}/api/admin`)).json()).settings;
  const pin=pinnedSettings.events[0].location;
  assert(Number.isFinite(pin.lat) && Number.isFinite(pin.lng));
  const map=invitationPage.locator('iframe[title="Mehndi venue map"]');
  assert.equal(new URL(await map.getAttribute('src')).searchParams.get('q'),`${pin.lat},${pin.lng}`);
  assert.equal(new URL(await invitationPage.getByRole('link',{name:'Directions',exact:true}).getAttribute('href')).searchParams.get('destination'),`${pin.lat},${pin.lng}`);
  await invitationPage.evaluate(()=>{
    Object.defineProperty(navigator,'share',{value:undefined,configurable:true});
    Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copiedLocation=text;}},configurable:true});
  });
  await invitationPage.getByRole('button',{name:'Share location'}).click();
  await invitationPage.getByText('Location link copied. Ready to share.').waitFor();
  assert.equal(new URL(await invitationPage.evaluate(()=>window.copiedLocation)).searchParams.get('query'),`${pin.lat},${pin.lng}`);
  assert.equal(await invitationPage.locator('.event-card').count(), 3);
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel(/^Date/).fill('2026-12-18');
  await page.locator('.event-settings-grid .settings-panel').first().getByLabel('Venue', { exact:true }).fill('Rose Banquet');
  await page.getByRole('button', { name:'Save all details' }).click();
  await page.waitForFunction(() => document.querySelector('.settings-bottom button').disabled);
  await invitationPage.evaluate(() => window.dispatchEvent(new Event('focus')));
  await invitationPage.getByText('18 December 2026', { exact:true }).waitFor();
  await invitationPage.waitForFunction(()=>document.querySelector('.event-mehndi .venue')?.textContent.includes('Rose Banquet'));
  await page.getByRole('tab', { name: 'Guest list' }).click();
  await page.getByRole('button', { name: 'Edit QA Wedding Guest' }).click();
  await page.getByLabel('Mehndi', { exact: true }).uncheck();
  await page.getByLabel('Baraat', { exact: true }).uncheck();
  await page.getByLabel('Without family').check();
  await page.getByRole('button', { name: 'Save changes' }).click();
  await page.getByRole('button', { name: 'Edit QA Wedding Guest' }).waitFor();
  await invitationPage.reload();
  await invitationPage.getByRole('heading', { name: 'QA Wedding Guest' }).waitFor();
  assert.equal(await invitationPage.locator('.event-card').count(), 1);
  assert.equal(await invitationPage.locator('.event-card h3').textContent(), 'Walima');
  assert.equal(await invitationPage.locator('.family-badge').count(), 0);
  await page.setViewportSize({ width: 375, height: 812 });
  await page.screenshot({ path: 'test-results/admin-mobile.png', fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('button', { name:'Add new guest' }).click();
  await page.screenshot({ path:'test-results/add-guest-mobile.png', fullPage:true });
  await page.getByRole('button', { name:'Close guest form' }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Remove QA Wedding Guest' }).click();
  await page.getByText('Guest removed.', { exact: true }).waitFor();
  assert.equal((await page.request.get(`${base}/api/invitation/${createdId}`)).status(), 404);
  createdId = null;
  await page.getByRole('tab', { name:'Dates & venues' }).click();
  await page.screenshot({ path:'test-results/settings-mobile.png', fullPage:true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('button', { name:'Sign out' }).click();
  await page.getByLabel('Username', { exact:true }).waitFor();
  assert.equal((await page.request.get(`${base}/api/admin`)).status(),401);
  const motionPage = await browser.newPage({ viewport:{ width:375,height:812 }, reducedMotion:'no-preference' });
  await motionPage.goto(base);
  await motionPage.getByRole('button', { name:'Ahmed Ali' }).click();
  await motionPage.locator('.envelope-overlay').waitFor();
  await motionPage.getByRole('heading', { name:'Ahmed Ali' }).waitFor();
  assert.equal(await motionPage.locator('.envelope-overlay').count(),0);
  for (const viewport of [{width:320,height:740},{width:812,height:375}]) {
    await motionPage.setViewportSize(viewport);
    await motionPage.goto(base);
    await motionPage.getByRole('button', { name:'Ahmed Ali' }).waitFor();
    assert(await motionPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Home overflow at ${viewport.width}px`);
  }
  assert.deepEqual(errors, []);
  console.log('PASS: /backend login, guest CRUD, family options, dates, venue/address, map pin, Google directions, share location, open-card refresh, responsive layouts, envelope animation, logout.');
} finally {
  await browser.close();
  await server.close();
}
